#!/usr/bin/env python3
"""
使用预定义的66个独特topic更新题库
"""
import urllib.request
import json
import time

NOTION_TOKEN = "YOUR_NOTION_TOKEN"
DB_ID = "bba82871-4fe1-4409-9f70-72f6bf27e7b3"

MAX_PART1 = 5
MAX_PART3 = 5

# 66个独特topic
TOPICS = [
    {"topic": "Describe a person who makes plans a lot", "part2": ["who he/she is", "how you knew him/her", "what plans he/she makes", "why planning is important to him/her"], "part1": ["Do you consider yourself a planner?", "How do you usually make plans?", "Do you prefer detailed plans or flexible ones?", "What happens when your plans change?", "Who makes plans for your family?"], "part3": ["Is planning important for success?", "Do young people plan enough?", "Should schools teach planning skills?", "How has technology changed planning?", "Can too much planning be bad?"]},
    {"topic": "Describe a famous person you would like to meet", "part2": ["who the person is", "what they are famous for", "why you want to meet them", "what you would say or do"], "part1": ["Do you follow any famous people?", "Who is famous in your country?", "Would you like to be famous someday?", "What do you think about celebrity culture?", "Do you watch celebrity news?"], "part3": ["What are the advantages of being famous?", "Do famous people have responsibilities?", "Is it fair to judge celebrities?", "Should celebrities be role models?", "Does fame bring happiness?"]},
    {"topic": "Describe a place you would like to visit", "part2": ["where the place is", "what you would do there", "who you would go with", "why you want to visit this place"], "part1": ["Do you like traveling?", "What places have you visited?", "Do you prefer mountains or beaches?", "How do you usually plan trips?", "What is your dream destination?"], "part3": ["Why do people travel?", "What are the benefits of travel?", "How has travel changed in recent years?", "Is tourism good for local people?", "Should travel be cheaper?"]},
    {"topic": "Describe a memorable trip you took", "part2": ["when and where you went", "who you traveled with", "what you did there", "why it was memorable"], "part1": ["Do you remember any special trips?", "What was your favorite trip?", "Who do you usually travel with?", "How do you feel when you travel?", "What do you usually pack for trips?"], "part3": ["What makes trips memorable?", "Are short trips as good as long ones?", "How do trips change us?", "Should children travel more?", "What should travel teach us?"]},
    {"topic": "Describe a skill you would like to learn", "part2": ["what skill you want to learn", "why you want to learn it", "how you would learn it", "when you would start"], "part1": ["What new skills have you learned recently?", "Do you think learning new skills is important?", "How do you usually learn new things?", "What skills are most valuable?", "Have you ever tried learning online?"], "part3": ["Why should people keep learning?", "What skills will be important in the future?", "Is it ever too late to learn?", "Should learning be fun?", "How can we learn more effectively?"]},
    {"topic": "Describe an interesting conversation you had", "part2": ["who you talked with", "where it happened", "what you talked about", "why it was interesting"], "part1": ["Do you enjoy talking with others?", "Who do you like to talk to?", "What topics interest you most?", "Do you prefer face-to-face or online chats?", "What makes a good conversation?"], "part3": ["Is conversation an art?", "How has social media changed conversations?", "Are people communicating less face-to-face?", "What makes someone a good listener?", "Should we talk more or listen more?"]},
    {"topic": "Describe something you did with your friends", "part2": ["what you did", "who you did it with", "when it happened", "how you felt about it"], "part1": ["What do you usually do with friends?", "How often do you meet friends?", "Do you prefer big groups or small groups?", "What is your best memory with friends?", "Do you stay in touch with old friends?"], "part3": ["Why are friendships important?", "What makes a good friend?", "Has social media changed friendships?", "Is it better to have many friends or a few close ones?", "How do friendships change as we age?"]},
    {"topic": "Describe a museum you visited", "part2": ["which museum it was", "where it was located", "what you saw there", "why you remember it"], "part1": ["Do you like visiting museums?", "What museums have you been to?", "Do you think museums are important?", "What is your favorite museum?", "Would you like to work in a museum?"], "part3": ["Should museums be free?", "Are museums only for tourists?", "What is the future of museums?", "Do museums teach more than books?", "Should children visit museums more?"]},
    {"topic": "Describe your favorite movie or TV series", "part2": ["what the movie/series is about", "when you first watched it", "why you like it", "who you watched it with"], "part1": ["Do you like watching movies?", "What is your favorite film?", "How often do you watch films?", "Do you prefer movies or series?", "Who is your favorite actor?"], "part3": ["Are movies or books better?", "How has streaming changed entertainment?", "Should there be more local content?", "What makes a movie successful?", "Is watching TV a waste of time?"]},
    {"topic": "Describe a piece of music important to you", "part2": ["what the music is", "when you first heard it", "why it is important", "what emotions it brings"], "part1": ["Do you like listening to music?", "What music do you prefer?", "When do you usually listen to music?", "Do you play any instruments?", "What music brings back memories?"], "part3": ["Is music education important?", "Can music change emotions?", "Will AI replace musicians?", "Should schools teach more music?", "Is pop music as valuable as classical?"]},
    {"topic": "Describe your favorite restaurant", "part2": ["where it is located", "what kind of food it serves", "who you usually go with", "why you like it"], "part1": ["Do you like eating out?", "What is your favorite restaurant?", "How often do you eat at restaurants?", "Do you prefer fast food or formal dining?", "What food do you usually order?"], "part3": ["Why do people like eating out?", "Is eating out becoming more popular?", "Should restaurants show calories?", "Is it healthy to eat out often?", "What makes a good restaurant?"]},
    {"topic": "Describe a healthy lifestyle habit you have", "part2": ["what habit you have", "how you started it", "how it benefits you", "when you do it"], "part1": ["Do you care about health?", "What healthy habits do you have?", "How often do you exercise?", "Do you sleep enough?", "What foods do you consider healthy?"], "part3": ["Why is health important?", "Should the government promote health?", "Is modern life making us unhealthy?", "Should health insurance be free?", "Can habits be changed?"]},
    {"topic": "Describe a party or celebration you attended", "part2": ["what kind of party it was", "who was there", "what happened", "how you felt"], "part1": ["Do you like parties?", "What kind of parties do you enjoy?", "Do you prefer dancing or talking at parties?", "What do you usually wear to parties?", "Do you celebrate birthdays?"], "part3": ["Why do people like parties?", "Are parties important for relationships?", "Has party culture changed over time?", "Are there too many commercial celebrations?", "Should we celebrate more traditional festivals?"]},
    {"topic": "Describe a historical place you visited", "part2": ["where it was located", "what you saw there", "when you visited", "what you learned"], "part1": ["Do you like historical places?", "What historical places have you visited?", "Do you think history is important?", "What is famous in your country?", "Would you like to live in the past?"], "part3": ["Should we preserve historical places?", "Is history taught enough in schools?", "Can historical places teach us about the future?", "Is too much emphasis placed on history?", "Should tourists visit historical sites?"]},
    {"topic": "Describe a teacher who influenced you", "part2": ["who the teacher was", "what subject they taught", "how they influenced you", "why they were special"], "part1": ["Who was your favorite teacher?", "What makes a good teacher?", "Do you still remember your teachers?", "How has your education changed you?", "What subjects did you like most?"], "part3": ["What is the role of teachers?", "Will AI replace teachers?", "Should teachers be paid more?", "How has education changed?", "Is homework necessary?"]},
    {"topic": "Describe a childhood memory", "part2": ["what the memory is about", "when it happened", "who was involved", "why you still remember it"], "part1": ["What is your earliest memory?", "What did you enjoy as a child?", "Who was your best friend as a child?", "Do you like being a child or adult more?", "What games did you play?"], "part3": ["Is childhood important for development?", "Are children today losing their childhood?", "Should children have more free time?", "How has childhood changed?", "Are parents putting too much pressure on children?"]},
    {"topic": "Describe something you collected", "part2": ["what you collected", "why you started collecting", "how long you collected", "what you did with it"], "part1": ["Do you collect anything?", "What do you like to collect?", "Do you think collecting is a good hobby?", "What is the most valuable thing you own?", "Would you collect things as an investment?"], "part3": ["Is collecting a good hobby?", "What do collections tell us about people?", "Should museums collect everything?", "Is collecting a waste of money?", "What will people collect in the future?"]},
    {"topic": "Describe a sport you enjoy playing or watching", "part2": ["what sport it is", "how long you have played/watched it", "who you play/watch it with", "why you enjoy it"], "part1": ["Do you like sports?", "What sports do you enjoy?", "Are you a player or a spectator?", "What sports were popular at school?", "Do you follow any sports teams?"], "part3": ["Why is sport important?", "Should everyone play a sport?", "Has sportsmanship declined?", "Should athletes be role models?", "Will esports replace traditional sports?"]},
    {"topic": "Describe your favorite book", "part2": ["what the book is about", "when you read it", "why it is your favorite", "what you learned from it"], "part1": ["Do you like reading?", "What is your favorite book?", "Do you prefer books or movies?", "How often do you read?", "What book are you reading now?"], "part3": ["Should everyone read more?", "Are people reading less because of the internet?", "Should schools require more reading?", "Is reading a good habit?", "What books should young people read?"]},
    {"topic": "Describe an adventure you experienced", "part2": ["what the adventure was", "where it happened", "who you were with", "how it ended"], "part1": ["Do you like adventures?", "What is the most adventurous thing you have done?", "Would you like to go on an adventure?", "What makes something an adventure?", "Do you prefer indoor or outdoor activities?"], "part3": ["Why do people seek adventure?", "Is adventure good for character development?", "Should young people have more adventures?", "Is adventure tourism safe?", "What is the difference between adventure and risk?"]},
    {"topic": "Describe a wedding you attended", "part2": ["whose wedding it was", "where it was held", "what happened", "how you felt"], "part1": ["Have you been to a wedding?", "What do weddings usually include?", "Do you like attending weddings?", "What did you wear?", "Do you have any wedding traditions?"], "part3": ["Is marriage important?", "Should wedding costs be reduced?", "Are traditional weddings better than modern ones?", "What is the role of weddings in society?", "Should same-sex marriage be allowed?"]},
    {"topic": "Describe a time you helped someone", "part2": ["who you helped", "what you did", "when it happened", "how you felt after"], "part1": ["Do you like helping others?", "Who do you usually help?", "What is the best way to help people?", "Have you volunteered before?", "Do you think helping others makes you happy?"], "part3": ["Why should we help others?", "Is charity a responsibility?", "Should helping be rewarded?", "Can we help too much?", "What is the difference between helping and interfering?"]},
    {"topic": "Describe your favorite season", "part2": ["which season it is", "what you usually do in this season", "what the weather is like", "why it is your favorite"], "part1": ["What is your favorite season?", "Do you prefer hot or cold weather?", "What do you usually do in this season?", "Does your favorite season affect your mood?", "What activities are best in each season?"], "part3": ["Is climate change affecting seasons?", "Do all countries have four seasons?", "Which season is best for health?", "How do seasons affect travel?", "Will seasons become less distinct?"]},
    {"topic": "Describe a natural scenery you like", "part2": ["where it is located", "what you see there", "how often you visit", "why it is beautiful"], "part1": ["Do you like nature?", "What natural scenery do you like?", "How often do you go to natural places?", "Do you prefer nature or cities?", "What is the most beautiful place you have seen?"], "part3": ["Should we protect natural scenery?", "Is tourism damaging nature?", "Should people live closer to nature?", "How does nature affect mental health?", "Who is responsible for protecting nature?"]},
    {"topic": "Describe a gift you gave or received", "part2": ["what the gift was", "who you gave it to or received it from", "why you chose it", "how it was received"], "part1": ["Do you like giving gifts?", "What is the best gift you ever received?", "What gifts do you usually give?", "Is gift-giving important in your culture?", "Do you prefer practical or sentimental gifts?"], "part3": ["Is gift-giving important in relationships?", "Should gifts be expensive?", "Is it the thought that counts?", "Has online shopping changed gift-giving?", "Should we regift presents?"]},
    {"topic": "Describe your morning routine", "part2": ["what you do in the morning", "what time you wake up", "how long it takes", "if you have breakfast"], "part1": ["Are you a morning person?", "What time do you usually wake up?", "What is your morning routine?", "Do you have breakfast?", "How do you feel without morning routines?"], "part3": ["Are routines important for productivity?", "Should school start later?", "Is skipping breakfast bad?", "Has modern life made mornings more stressful?", "Should work hours be flexible?"]},
    {"topic": "Describe a skill you learned from someone", "part2": ["what skill you learned", "who taught you", "how you learned it", "how useful it is now"], "part1": ["Who taught you your most useful skill?", "What skills have you learned from family?", "Do you prefer learning from people or books?", "What skill would you like to learn?", "Have you taught any skill to others?"], "part3": ["Is learning from experience important?", "Should the young learn from the old?", "How has apprenticeship changed?", "Can anyone learn anything?", "Is patience needed for learning?"]},
    {"topic": "Describe a rule at school or work", "part2": ["what the rule is", "why it was created", "if you agree with it", "what happens if you break it"], "part1": ["What rules exist at your school or workplace?", "Do you agree with all rules?", "Are there any unnecessary rules?", "What happens if rules are broken?", "Should rules be strictly enforced?"], "part3": ["Are there too many rules in modern society?", "Is freedom more important than rules?", "Do rules limit creativity?", "Should children have more freedom?", "How do rules affect behavior?"]},
    {"topic": "Describe your favorite holiday", "part2": ["which holiday it is", "how you usually celebrate it", "who you celebrate with", "why it is your favorite"], "part1": ["What is your favorite holiday?", "How do you celebrate holidays?", "Do you prefer traditional or commercial holidays?", "What is the most important holiday in your country?", "Do you like staying home or traveling during holidays?"], "part3": ["Are holidays important for families?", "Has commercialism ruined holidays?", "Should holidays be longer?", "Will holidays change in the future?", "Do holidays reflect culture?"]},
    {"topic": "Describe a time you felt proud", "part2": ["what happened", "where it was", "who was there", "why it made you proud"], "part1": ["What makes you feel proud?", "Do you easily feel proud of yourself?", "What achievement are you most proud of?", "Do you share your achievements with others?", "Is being proud of yourself important?"], "part3": ["Is pride a positive emotion?", "Should we celebrate achievements more?", "Does pride sometimes become negative?", "How should parents make children feel proud?", "Is it good to be proud of your country?"]},
    {"topic": "Describe a vehicle you would like to buy", "part2": ["what vehicle it is", "why you want it", "when you plan to buy it", "how you would use it"], "part1": ["Do you have a car or bike?", "What is your dream vehicle?", "Is owning a vehicle necessary?", "What matters most when buying a vehicle?", "Will cars become obsolete?"], "part3": ["Should the government limit car ownership?", "Is traffic getting worse?", "Will self-driving cars change transport?", "Are electric cars the future?", "Should public transport be free?"]},
    {"topic": "Describe your favorite animal", "part2": ["what animal it is", "why you like it", "if you have one as a pet", "what makes it special"], "part1": ["Do you like animals?", "What is your favorite animal?", "Do you have any pets?", "Have you ever been to a zoo?", "What animal would you like to be?"], "part3": ["Should people keep pets?", "Is it ethical to use animals for entertainment?", "Are zoos good or bad?", "Will animals become extinct?", "Should we eat animals?"]},
    {"topic": "Describe a newspaper or magazine you read", "part2": ["what it is about", "how often you read it", "what you learn from it", "why you subscribed"], "part1": ["Do you read newspapers or magazines?", "What is your favorite publication?", "Do you prefer print or digital?", "How much time do you spend reading news?", "Do you trust the news?"], "part3": ["Is the news reliable?", "Should children read news?", "Has the internet killed traditional media?", "Is fake news a problem?", "Should journalism be a profession?"]},
    {"topic": "Describe an app on your phone", "part2": ["what the app does", "how long you have used it", "why you use it", "how it helps you"], "part1": ["What apps do you use most?", "Do you think apps are useful?", "How many apps do you have?", "Would you give up your phone for a week?", "Do apps collect too much data?"], "part3": ["Are apps changing behavior?", "Should there be age limits for apps?", "Will apps replace websites?", "Is app addiction real?", "Should app stores be regulated?"]},
    {"topic": "Describe a recent decision you made", "part2": ["what the decision was", "what factors you considered", "how you made it", "if it was the right choice"], "part1": ["Do you make decisions easily?", "What was your last important decision?", "How do you usually make choices?", "Do you regret many decisions?", "Who helps you make decisions?"], "part3": ["Are we making too many choices?", "Is too much choice bad?", "Should important decisions be made by experts?", "How do first impressions affect decisions?", "Can AI make better decisions than humans?"]},
    {"topic": "Describe your favorite café", "part2": ["where it is located", "what drinks you order", "who you go with", "why you like it"], "part1": ["Do you like cafés?", "What is your favorite café?", "How often do you visit cafés?", "Do you prefer quiet or noisy places?", "What do you usually order at a café?"], "part3": ["Is the café culture growing?", "Are cafés good places for meetings?", "Should cafés provide free WiFi?", "Is working in cafés productive?", "Will cafés survive online meetings?"]},
    {"topic": "Describe a video game you played", "part2": ["what game it is", "when you started playing", "who you play with", "why you enjoy it"], "part1": ["Do you play video games?", "What is your favorite game?", "How long do you spend gaming?", "Do you play on console or phone?", "Is gaming a good hobby?"], "part3": ["Is gaming good or bad for you?", "Should gaming be a sport?", "Will VR replace traditional gaming?", "Are games becoming too violent?", "Should parents limit children's gaming?"]},
    {"topic": "Describe a website you often visit", "part2": ["what the website is", "what you do there", "how often you visit", "why you like it"], "part1": ["What websites do you use daily?", "Do you prefer websites or apps?", "How has the internet changed your life?", "What would happen without the internet?", "Do you trust online information?"], "part3": ["Is the internet safe for children?", "Should internet access be a right?", "Will AI replace websites?", "Is online privacy possible?", "How will the internet evolve?"]},
    {"topic": "Describe a photo you took", "part2": ["what the photo shows", "when you took it", "where you were", "why it is memorable"], "part1": ["Do you like taking photos?", "What photos do you usually take?", "Do you prefer photos of people or places?", "Do you edit your photos?", "What is the best photo you have taken?"], "part3": ["Is photography an art?", "Should photos be edited?", "Are we taking too many photos?", "Will cameras replace memory?", "Should photographers be credited?"]},
    {"topic": "Describe your favorite type of weather", "part2": ["what weather you prefer", "what activities you do in this weather", "how it affects your mood", "why you like it"], "part1": ["What is your favorite weather?", "Does weather affect your mood?", "What do you do on rainy days?", "Do you prefer summer or winter?", "What is the weather usually like in your city?"], "part3": ["Is weather related to mood?", "Can weather affect productivity?", "Has climate change affected local weather?", "Should cities have more green spaces?", "Will weather prediction improve?"]},
    {"topic": "Describe a time you waited for something", "part2": ["what you waited for", "where you waited", "how long you waited", "how you felt"], "part1": ["Are you a patient person?", "What do you usually wait for?", "Do you hate waiting in lines?", "What is the longest you have waited?", "How do you feel while waiting?"], "part3": ["Is patience a virtue?", "Has technology made us less patient?", "Should waiting times be shorter?", "Is waiting a waste of time?", "Can waiting be productive?"]},
    {"topic": "Describe your favorite school subject", "part2": ["what the subject is", "why you liked it", "who taught it", "what you learned"], "part1": ["What was your favorite subject?", "Did you like all subjects?", "Were you good at the subject?", "Did you have private tutoring?", "What subject was most useful?"], "part3": ["Should all subjects be equally important?", "Is the education system outdated?", "Should we teach practical skills?", "How will education change?", "Is memorization still important?"]},
    {"topic": "Describe a time you felt surprised", "part2": ["what happened", "where it was", "who was involved", "how you reacted"], "part1": ["What surprises you easily?", "Do you like surprises?", "What was your biggest surprise?", "Are you good at hiding emotions?", "Do surprises make life interesting?"], "part3": ["Is surprise a good or bad emotion?", "Can we live without surprises?", "Should life be predictable?", "Do children need more surprises?", "Is expecting the unexpected reasonable?"]},
    {"topic": "Describe a place in your city you like", "part2": ["where the place is", "what you can do there", "how often you go", "why you like it"], "part1": ["What places in your city do you like?", "Is your city worth living in?", "What is the best place in your city?", "Do you know your city well?", "Has your city changed recently?"], "part3": ["Should cities be planned or organic?", "Are cities making people lonely?", "Will cities grow or shrink?", "Should cities have more public spaces?", "Are smart cities the future?"]},
    {"topic": "Describe a family tradition", "part2": ["what the tradition is", "how long it has existed", "who participates", "why it is important"], "part1": ["Does your family have traditions?", "What traditions does your family have?", "Do you follow all family traditions?", "Are family traditions important?", "Have any traditions changed over time?"], "part3": ["Are family traditions dying out?", "Should traditions be preserved?", "Is it good to have family rituals?", "How do traditions bind families?", "Can new traditions be created?"]},
    {"topic": "Describe a piece of clothing you like", "part2": ["what it looks like", "where you got it", "when you wear it", "why it is your favorite"], "part1": ["What is your favorite piece of clothing?", "Do you care about fashion?", "What do you usually wear?", "Do you prefer comfortable or stylish clothes?", "How much do you spend on clothes?"], "part3": ["Is fast fashion a problem?", "Should clothes be more sustainable?", "Does clothing express identity?", "Will traditional clothing disappear?", "Should schools have uniforms?"]},
    {"topic": "Describe a DIY project you did", "part2": ["what you made", "how you did it", "what tools you used", "how it turned out"], "part1": ["Do you enjoy DIY projects?", "What DIY have you done?", "Are you good at fixing things?", "Do you prefer doing things yourself or hiring others?", "What tools do you have?"], "part3": ["Is DIY a useful skill?", "Should schools teach DIY?", "Has DIY become more popular?", "Will robots replace handymen?", "Is it cheaper to do it yourself?"]},
    {"topic": "Describe your favorite fruit", "part2": ["what fruit it is", "when you usually eat it", "where it grows", "why you like it"], "part1": ["What is your favorite fruit?", "Do you eat fruit every day?", "What fruit did you like as a child?", "Do you prefer fresh or processed fruit?", "Is fruit expensive in your country?"], "part3": ["Should fruit be part of daily diet?", "Is organic fruit worth the extra cost?", "Has fruit quality declined?", "Will fruit become a luxury?", "Should governments subsidize fruit?"]},
    {"topic": "Describe a time you lost something", "part2": ["what you lost", "where you lost it", "how you felt", "if you found it"], "part1": ["Have you ever lost something?", "What do you usually lose?", "How do you keep track of things?", "Do you have a system for important items?", "What is the most valuable thing you lost?"], "part3": ["Is losing things a modern problem?", "Can technology prevent losing things?", "Should we own less?", "Is minimalism a good idea?", "Do children need to learn organization?"]},
    {"topic": "Describe a song that reminds you of someone", "part2": ["what the song is", "who it reminds you of", "why it is connected", "when you listen to it"], "part1": ["What song reminds you of someone?", "Do you have a song for each memory?", "What music brings back memories?", "Do you listen to old songs?", "Can music trigger memories?"], "part3": ["Is music linked to memory?", "Do songs have longer lasting impact than photos?", "Should we update our music playlists?", "Will streaming change how we remember music?", "Is music more powerful than words?"]},
    {"topic": "Describe your favorite hot beverage", "part2": ["what it is", "when you drink it", "where you have it", "why you like it"], "part1": ["What is your favorite hot drink?", "Do you drink tea or coffee?", "How many cups do you have daily?", "Do you have a ritual for making drinks?", "What is the tradition of your favorite drink?"], "part3": ["Is coffee culture positive?", "Should children drink tea or coffee?", "Has the coffee shop trend grown?", "Will AI make perfect coffee?", "Is tea or coffee better for health?"]},
    {"topic": "Describe a movie scene you remember", "part2": ["what the scene is about", "what movie it is from", "why it is memorable", "how it made you feel"], "part1": ["What movie scene do you remember?", "Do sad or happy scenes stay longer?", "Do you rewatch movies?", "What is the most emotional scene?", "Can a single scene make a movie?"], "part3": ["Are movies getting more or less emotional?", "Should movies have age ratings?", "Do movies influence behavior?", "Is cinema dying?", "Will VR replace movie theaters?"]},
    {"topic": "Describe a person who is good at cooking", "part2": ["who the person is", "what they cook", "how you know them", "what makes their cooking special"], "part1": ["Do you like cooking?", "Who cooks in your family?", "What is the best dish you have tasted?", "Can you cook well?", "Would you like to be a chef?"], "part3": ["Is cooking an important skill?", "Should cooking be taught in schools?", "Will robots replace cooks?", "Is homemade food always healthier?", "Should everyone learn to cook?"]},
    {"topic": "Describe a time you had to be patient", "part2": ["what required patience", "how long it lasted", "how you stayed patient", "what the outcome was"], "part1": ["Do you consider yourself patient?", "What tests your patience?", "Do you wait well in traffic?", "What makes you lose patience?", "Is patience a skill or personality trait?"], "part3": ["Is patience more important now than before?", "Does modern life test patience?", "Can patience be learned?", "Is patience linked to success?", "Should children be taught patience?"]},
    {"topic": "Describe your favorite month", "part2": ["which month it is", "what happens in this month", "why it is special", "what you do differently in this month"], "part1": ["What is your favorite month?", "Does your favorite month have holidays?", "What is the weather like then?", "Do you have birthdays in this month?", "What activities do you do in this month?"], "part3": ["Are seasons more important than months?", "Should calendar system change?", "Do months affect mood?", "Will work schedules change months?", "Is the concept of months universal?"]},
    {"topic": "Describe a garden or park you visited", "part2": ["where it was located", "what you saw there", "who you went with", "why you remember it"], "part1": ["Do you like parks and gardens?", "What is your favorite park?", "How often do you visit parks?", "Do you prefer parks or gardens?", "What do you do in parks?"], "part3": ["Are parks important for cities?", "Should parks be free?", "Is gardening a good hobby?", "Will green spaces disappear?", "Should we have more urban gardens?"]},
    {"topic": "Describe a time you changed your opinion", "part2": ["what the issue was", "what your original opinion was", "what changed your mind", "how you feel about it now"], "part1": ["Do you change your opinions easily?", "What was an opinion you changed?", "Do you share controversial opinions?", "Is it weak to change your mind?", "What influences opinions most?"], "part3": ["Are people too stubborn nowadays?", "Should opinions be evidence-based?", "Is changing your mind a sign of growth?", "Can opinions be changed by discussion?", "Are we influenced too much by social media?"]},
    {"topic": "Describe your favorite board game", "part2": ["what the game is", "how you play it", "who you usually play with", "why it is your favorite"], "part1": ["Do you like board games?", "What board games do you know?", "How often do you play board games?", "Are board games popular in your country?", "Do you prefer physical or digital games?"], "part3": ["Are board games good for families?", "Is gaming replacing board games?", "Should board games be educational?", "Will board games survive?", "Are traditional games being forgotten?"]},
    {"topic": "Describe a time you felt nervous", "part2": ["what caused the nervousness", "where you were", "how you managed it", "what happened after"], "part1": ["Do you get nervous easily?", "What makes you nervous?", "Do you show nervousness physically?", "How do you deal with nervousness?", "Is nervousness helpful or harmful?"], "part3": ["Is nervousness different from anxiety?", "Can nervousness be overcome?", "Should we hide nervousness?", "Is nervousness linked to performance?", "Do children experience more nervousness today?"]},
    {"topic": "Describe a TV commercial you remember", "part2": ["what it was about", "when you saw it", "why it was memorable", "what product it advertised"], "part1": ["Do you watch TV commercials?", "What commercial do you remember?", "Do commercials influence your purchases?", "Are commercials annoying?", "What makes a good commercial?"], "part3": ["Are commercials misleading?", "Should advertising be more regulated?", "Has internet killed TV commercials?", "Is advertising necessary for free content?", "Will AI create better commercials?"]},
    {"topic": "Describe a place near water", "part2": ["where the place is", "what you do there", "how often you visit", "why you like it"], "part1": ["Do you like places near water?", "What places near water have you visited?", "Do you live near any water?", "What activities can you do near water?", "Do you prefer beach or lake?"], "part3": ["Should water spaces be public?", "Is water tourism growing?", "Are water sports safe?", "Will water become scarce?", "Should we protect water ecosystems?"]},
    {"topic": "Describe a book you want to read", "part2": ["what the book is about", "why you want to read it", "when you plan to read it", "what type of book it is"], "part1": ["What book is on your reading list?", "Do you have a book you have been meaning to read?", "How many books do you read per year?", "Do you set reading goals?", "What type of books do you prefer?"], "part3": ["Should we read more books?", "Are e-books replacing printed books?", "Is reading becoming a lost art?", "Should reading be prescribed for health?", "Will reading survive digital distraction?"]},
    {"topic": "Describe a public holiday in your country", "part2": ["which holiday it is", "how people celebrate", "if you have time off", "what you usually do"], "part1": ["What public holidays does your country have?", "Which is your favorite holiday?", "Do you get enough holidays?", "How do you usually spend holidays?", "Are holidays important for your country?"], "part3": ["Should there be more public holidays?", "Are holidays too commercial?", "Should holidays be moved to weekends?", "Will holidays change in the future?", "Are traditional holidays being forgotten?"]},
    {"topic": "Describe a time you learned something new", "part2": ["what you learned", "how you learned it", "who helped you learn", "how useful it has been"], "part1": ["What did you learn recently?", "Do you enjoy learning new things?", "How do you usually learn?", "What skills do you want to learn?", "Is learning fun or stressful?"], "part3": ["Is learning more important than ever?", "Can we learn too much?", "Should learning be lifelong?", "How will AI affect learning?", "Is curiosity important for learning?"]},
    {"topic": "Describe your favorite ice cream flavor", "part2": ["what flavor it is", "where you usually get it", "when you eat it", "why it is your favorite"], "part1": ["Do you like ice cream?", "What is your favorite flavor?", "How often do you eat ice cream?", "Do you prefer traditional or exotic flavors?", "Is ice cream popular in your country?"], "part3": ["Is ice cream healthy or unhealthy?", "Should ice cream have sugar warnings?", "Will ice cream be replaced by healthier options?", "Is the ice cream industry sustainable?", "Can ice cream be made without cows?"]}
]

def api(url, method="GET", data=None):
    req = urllib.request.Request(url, data=data.encode() if data else None, method=method)
    req.add_header("Authorization", f"Bearer {NOTION_TOKEN}")
    req.add_header("Notion-Version", "2022-06-28")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.load(resp)
    except: return None

def delete_all_blocks(page_id):
    while True:
        blocks = api(f"https://api.notion.com/v1/blocks/{page_id}/children")
        if not blocks or not blocks.get("results"):
            break
        for b in blocks["results"]:
            api(f"https://api.notion.com/v1/blocks/{b.get('id')}", method="DELETE")
            time.sleep(0.05)
        time.sleep(0.2)

def add_blocks(page_id, topic_data):
    blocks = []
    
    # Part 1
    blocks.append({"object": "block", "type": "heading_1", "heading_1": {"rich_text": [{"text": {"content": "Part 1"}}]}})
    blocks.append({"object": "block", "type": "heading_3", "heading_3": {"rich_text": [{"text": {"content": "Topic"}}]}})
    for q in topic_data["part1"][:MAX_PART1]:
        blocks.append({"object": "block", "type": "bulleted_list_item", "bulleted_list_item": {"rich_text": [{"text": {"content": q}}]}})
    
    # Part 2
    blocks.append({"object": "block", "type": "heading_1", "heading_1": {"rich_text": [{"text": {"content": "Part 2"}}]}})
    blocks.append({"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"text": {"content": topic_data["topic"]}}]}})
    blocks.append({"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"text": {"content": "You should say:"}}]}})
    for p in topic_data["part2"]:
        blocks.append({"object": "block", "type": "bulleted_list_item", "bulleted_list_item": {"rich_text": [{"text": {"content": p}}]}})
    
    # Part 3
    blocks.append({"object": "block", "type": "heading_1", "heading_1": {"rich_text": [{"text": {"content": "Part 3"}}]}})
    for i, q in enumerate(topic_data["part3"][:MAX_PART3], 1):
        blocks.append({"object": "block", "type": "numbered_list_item", "numbered_list_item": {"rich_text": [{"text": {"content": f"{i}. {q}"}}]}})
    
    # Append
    url = f"https://api.notion.com/v1/blocks/{page_id}/children"
    for i in range(0, len(blocks), 100):
        batch = blocks[i:i+100]
        api(url, method="PATCH", data=json.dumps({"children": batch}))
        time.sleep(0.3)

def main():
    print("=" * 60)
    print("为66个Test更新独特内容")
    print("=" * 60)
    
    # 获取所有页面
    result = api(f"https://api.notion.com/v1/databases/{DB_ID}/query", method="POST", data=json.dumps({"page_size": 100}))
    pages = result.get("results", [])
    
    print(f"\n获取到 {len(pages)} 个Test")
    
    success = 0
    fail = 0
    
    for i, page in enumerate(pages):
        props = page.get("properties", {})
        num = props.get("编号", {}).get("number", 0)
        page_id = page.get("id")
        
        topic_data = TOPICS[i % len(TOPICS)]
        
        print(f"[{i+1}/66] Test {num:02d}: {topic_data['topic'][:30]}...", end=" ", flush=True)
        
        # 删除旧内容
        delete_all_blocks(page_id)
        
        # 添加新内容
        add_blocks(page_id, topic_data)
        
        print("✅")
        success += 1
        time.sleep(0.5)
    
    print(f"\n完成! 成功: {success}, 失败: {fail}")

if __name__ == "__main__":
    main()
